INSERT INTO DonationReadState VALUES ('PENDING');
INSERT INTO DonationReadState VALUES ('AMOUNT_READ');
INSERT INTO DonationReadState VALUES ('COMMENT_READ');
INSERT INTO DonationReadState VALUES ('FLAGGED');
